name: Creazione API Spec repository da Template

on:
  create

jobs:
    template_check:
      runs-on: ubuntu-latest
      steps:
        - name: Repository creation test
          if: contains(github.event.description, 'openapi-template')
          run: |
            echo "Creating repoisitory from OpenAPI Template "
            echo ${github.event}
            echo "${github.event} File" >> testfile.txt
