name: Creazione API Spec repository da Template
on:
  push:
    branches: [ "main" ]
jobs:
    template_check:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Write file
        if: ${{ contains(github.ref, 'refs/heads/main') && github.event.created == true && contains(github.event.repository.description, 'corebanking') }}
        env:
          FILIERA: ${{ github.event.description }}
        run: 
          echo "$FILIERA" > test.txt
      - name: Commit changes
        if: ${{ contains(github.ref, 'refs/heads/main') && github.event.created == true && contains(github.event.repository.description, 'corebanking') }}      
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "$AUTHOR"
          git add test.txt
          git commit -m "Add test.txt"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR:  ${{ github.event.commits[0].author.name }}
          EMAIL:  ${{ github.event.commits[0].author.email }}
